Nodejs-week3
Divyajg/hyf-homework pull request #19
Opened 2021-10-28 11:27 UTC by Divyajg

2021-11-07 10:32 UTC, dsamourkasidis commented on nodejs/week3/homework/warmup/index.js
> +    let addResult = values.reduce((total, value) => parseInt(total) + parseInt(value));
good job using reduce!
addResult can be a const :)

2021-11-07 10:32 UTC, dsamourkasidis commented on nodejs/week3/homework/warmup/index.js
> +    const subResult = parseInt(firstParam) - parseInt(secondParam);
You couldn't use reduce here as well?

2021-11-07 10:37 UTC, dsamourkasidis commented on nodejs/week3/homework/warmup/index.js
> +    res.send(`Result of division = ${divideResult}`);
An idea to avoid copy pasting the same code, for instance
```
let divideResult = values.reduce((total, value) => parseInt(total) / parseInt(value));
```
would be do to create a separate function, eg divideNumbers, and call that one both in the get and the post request.
That way, it's cleaner, and if say you want to add an extra step in your division, you will only have to change it in one place

2021-11-07 10:38 UTC, dsamourkasidis requested changes
Great work Divya! 
Go through my comment and let me know if you're unsure about anything :)

2021-11-07 10:50 UTC, dsamourkasidis commented on nodejs/week3/homework/warmup/index.js
> +app.use(bodyParser.urlencoded({ extended: true }));
in latest express versions, you don't have to require the bodyParser, you can just do this:
```
app.use(express.urlencoded({ extended: true }));
```

2021-11-08 11:24 UTC, Divyajg commented on nodejs/week3/homework/warmup/index.js
> +    const subResult = parseInt(firstParam) - parseInt(secondParam);
Yes, I can, just tried differently!.

2021-11-08 11:25 UTC, Divyajg commented on nodejs/week3/homework/warmup/index.js
> +    res.send(`Result of division = ${divideResult}`);
Okay

2021-11-09 12:45 UTC, Divyajg commented
Hey @dsamourkasidis , Please have a look at the updated code.
Thank you.

2021-11-09 19:35 UTC, dsamourkasidis approved these changes
Looks great Divya, good job :+1:  You can merge it!

2021-11-10 12:24 UTC, merged