Javascript javascript1 week3
Divyajg/hyf-homework pull request #6
Opened 2021-07-15 10:32 UTC by Divyajg

2021-07-20 09:29 UTC, TITHI1244 requested changes
Very good job. A few improvements needed. Try to implement those 👍

2021-07-20 09:29 UTC, TITHI1244 commented on javascript/javascript1/week3/travel.js
> +function travel() {
Try to name the functions more descriptive. Think about what it is doing here, and start with a verb, maybe calculateTravelTime.

2021-07-20 09:29 UTC, TITHI1244 commented on javascript/javascript1/week3/travel.js
> +    let result2 = (travelInformation.destinationDistance % travelInformation.speed);
You are not asked to use the variable `travelInformation` inside the function directly. You were supposed to use it as the function parameter. Try to pass it as the function argument.

2021-07-20 09:29 UTC, TITHI1244 commented on javascript/javascript1/week3/travel.js
> +const travelTime = travel(travelInformation);
JavaScript is very flexible, so it's not showing you any error. But your function `travel` does not accept any parameter and here you are passing one argument. Try to fix it :)

2021-07-20 09:29 UTC, TITHI1244 commented on javascript/javascript1/week3/series.js
> +function percentage() {
Again, a little more descriptive function name :)

2021-07-20 09:29 UTC, TITHI1244 commented on javascript/javascript1/week3/series.js
> +const minInLifespan = exactLifespan = hoursInLifespan * 60;
Where does `exactLifespan` come from and why do you need that? If you need that then remove the first variable `minInLifespan`.

2021-07-20 09:29 UTC, TITHI1244 commented on javascript/javascript1/week3/notes.js
> +
Nice 👍

2021-07-20 09:29 UTC, TITHI1244 commented on javascript/javascript1/week3/smartphone.js
> +function showStatus() {
I think, you meant to do `function showStatus(activities)` here, right?

2021-07-22 08:23 UTC, TITHI1244 approved these changes
Nice job 👍

2021-07-22 08:23 UTC, TITHI1244 commented on javascript/javascript1/week3/item-array-removal.js
> +    if (names[i] === nameToRemove) {
👍

2021-07-22 08:23 UTC, TITHI1244 commented on javascript/javascript1/week3/series.js
> +function percentageOfTimeSpentOnSeries(seriesDurations) {
I would name it `calculateTimeSpentOnSeries` starting with the verb calculate :)

2021-07-22 08:23 UTC, TITHI1244 commented on javascript/javascript1/week3/smartphone.js
> +function showStatus(activities) {
👍

2021-07-22 08:23 UTC, TITHI1244 commented on javascript/javascript1/week3/travel.js
> +function calculateTravelTime(travelInformation) {
👍

2021-07-22 08:27 UTC, Divyajg commented on javascript/javascript1/week3/series.js
> +function percentageOfTimeSpentOnSeries(seriesDurations) {
Thank you, I will remember these for next time.

2021-07-22 08:27 UTC, merged